### ISSUE TITLE
把提示换成其他自带的app是不是更稳一点，因为每个ios版本的提示内容都不一样

### ISSUE THREAD

**Issue by boli2017** [invalidunit/chflags_trollhelper#12]

**Comment by invalidunit** [comment]
不知道你想说什么，难道其他 app 不一样的吗，不照样更新期间会被系统更新？
这个教程的核心是锁，让系统更新期间无法写入 Tips（提示）app，或者你换成别的也可以，但是无论哪个系统，应该提示都是最无用的，所以最通用
