### ISSUE TITLE
无法黏贴进vm_stat

### ISSUE THREAD

**Issue by dan3577** [invalidunit/chflags_trollhelper#15]
08.将刚刚合成的命令复制到剪切板

09.找到 /usr/bin/vm_stat 并且点击运行

10.粘贴刚刚的命令，回车运行

这会锁定住 Tips，防止系统更新时将其修改为新版本的 Tips

第10步。长按黏贴不了命令进终端

**Comment by dan3577** [comment]
![image](https://github.com/invalidunit/chflags_trollhelper/assets/52194615/5af30257-b6bb-4b07-8199-34672f6c80ab)
长按黏贴无反应

**Comment by invalidunit** [comment]
> ![image](https://private-user-images.githubusercontent.com/52194615/288353745-5af30257-b6bb-4b07-8199-34672f6c80ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTU0OTUsIm5iZiI6MTcwMTg1NTE5NSwicGF0aCI6Ii81MjE5NDYxNS8yODgzNTM3NDUtNWFmMzAyNTctYjZiYi00YjA3LTgxOTktMzQ2NzJmNmM4MGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5MzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZWZiM2I4YmE3NGQyNmNjZDA2ODdhZmEzYTgwZDVmMGE5MTNhMjViMjJmMTM5ZTM0OWQ0ZGE3NWNlOThmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mEn8KckLpwDIt-32Xrj1_f2mw65Hpc9kvqMmn6bnWYA) 长按黏贴无反应

已越狱？一般出现在15的越狱设备上，你可以清越狱后再来，或者尝试使用越狱后的终端，newterm 什么的（自行使用 sudo su提权到 root 后再运行）
