### ISSUE TITLE
两台设备更新之后tips app消失

### ISSUE THREAD

**Issue by Takagoz** [invalidunit/chflags_trollhelper#4]
iphone 13pro 16.1.2更新到16.6.1，ipad pro 2018 15.0更新到16.6.1，之前完全按照教程设置，通过fliza固定了tips，并且测试了删除tips报错和教程中一样，开启了监管模式并且保留了trollstore和trollhelper(tips app)的后台进行延迟更新到16.6.1。
两台设备更新完之后出现了同样的问题：
升级完毕后应用列表的tips app不见了，进入AppStore搜索tips显示已购买可下载状态，点击下载无效。所有原系统trollstore安装的app无法打开：13pro显示为点击无效，ipad pro显示为已无法使用。
无法通过固定的tips重新install trollstore，无法通过trollstore重建图标缓存，无法通过fliza关闭监管模式。这种情况是不是只能等opa334开发新的安装方法才能解决了？

**Comment by invalidunit** [comment]
> iphone 13pro 16.1.2更新到16.6.1，ipad pro 2018 15.0更新到16.6.1，之前完全按照教程设置，通过fliza固定了tips，并且测试了删除tips报错和教程中一样，开启了监管模式并且保留了trollstore和trollhelper(tips app)的后台进行延迟更新到16.6.1。 两台设备更新完之后出现了同样的问题： 升级完毕后应用列表的tips app不见了，进入AppStore搜索tips显示已购买可下载状态，点击下载无效。所有原系统trollstore安装的app无法打开：13pro显示为点击无效，ipad pro显示为已无法使用。 无法通过固定的tips重新install trollstore，无法通过trollstore重建图标缓存，无法通过fliza关闭监管模式。这种情况是不是只能等opa334开发新的安装方法才能解决了？

是的，你目前只能等待 opa334 或者其他人找到新的安装方法。
根据你的描述，我猜测你与某些人一样，执行 chflags 命令时没移除后后面的 /Tips.app，应该锁定上层文件夹而不是 Tips.app 本身

**Comment by Takagoz** [comment]
> > iphone 13pro 16.1.2更新到16.6.1，ipad pro 2018 15.0更新到16.6.1，之前完全按照教程设置，通过fliza固定了tips，并且测试了删除tips报错和教程中一样，开启了监管模式并且保留了trollstore和trollhelper(tips app)的后台进行延迟更新到16.6.1。 两台设备更新完之后出现了同样的问题： 升级完毕后应用列表的tips app不见了，进入AppStore搜索tips显示已购买可下载状态，点击下载无效。所有原系统trollstore安装的app无法打开：13pro显示为点击无效，ipad pro显示为已无法使用。 无法通过固定的tips重新install trollstore，无法通过trollstore重建图标缓存，无法通过fliza关闭监管模式。这种情况是不是只能等opa334开发新的安装方法才能解决了？
> 
> 是的，你目前只能等待 opa334 或者其他人找到新的安装方法。 根据你的描述，我猜测你与某些人一样，执行 chflags 命令时没移除后后面的 /Tips.app，应该锁定上层文件夹而不是 Tips.app 本身

你好，刚刚我查看了13pro的后台发现还有trollstore，测试可以用后台打开，我将trollhelper改成了fitness，之后可以成功使用trollstore安装的程序了。目前ipad更新之后后台是空的，可能无法复现这种方法来激活trollstore了，我猜可能是运行内存只有4g的原因？。

我可以确定我在执行命令的时候是移除了/tips.app。
通过fliza的历史，看到虽然tips app消失了，store也显示已购买可下载状态（下载无效），但是fliza里面依然有tips的文件夹，通过教程的取消固定之后，可以才能正常下载。这也能说明我之前的操作应该是没问题的。

**Comment by invalidunit** [comment]
> > > iphone 13pro 16.1.2更新到16.6.1，ipad pro 2018 15.0更新到16.6.1，之前完全按照教程设置，通过fliza固定了tips，并且测试了删除tips报错和教程中一样，开启了监管模式并且保留了trollstore和trollhelper(tips app)的后台进行延迟更新到16.6.1。 两台设备更新完之后出现了同样的问题： 升级完毕后应用列表的tips app不见了，进入AppStore搜索tips显示已购买可下载状态，点击下载无效。所有原系统trollstore安装的app无法打开：13pro显示为点击无效，ipad pro显示为已无法使用。 无法通过固定的tips重新install trollstore，无法通过trollstore重建图标缓存，无法通过fliza关闭监管模式。这种情况是不是只能等opa334开发新的安装方法才能解决了？
> > 
> > 
> > 是的，你目前只能等待 opa334 或者其他人找到新的安装方法。 根据你的描述，我猜测你与某些人一样，执行 chflags 命令时没移除后后面的 /Tips.app，应该锁定上层文件夹而不是 Tips.app 本身
> 
> 你好，刚刚我查看了13pro的后台发现还有trollstore，测试可以用后台打开，我将trollhelper改成了fitness，之后可以成功使用trollstore安装的程序了。目前ipad更新之后后台是空的，可能无法复现这种方法来激活trollstore了，我猜可能是运行内存只有4g的原因？。
> 
> 我可以确定我在执行命令的时候是移除了/tips.app。 通过fliza的历史，看到虽然tips app消失了，store也显示已购买可下载状态（下载无效），但是fliza里面依然有tips的文件夹，通过教程的取消固定之后，可以才能正常下载。这也能说明我之前的操作应该是没问题的。

好吧，那所以最保险还是两种方法混用，因为我也不能保证我方法 100% 成功

**Comment by zlfengshare** [comment]
> > > iphone 13pro 16.1.2更新到16.6.1，ipad pro 2018 15.0更新到16.6.1，之前完全按照教程设置，通过fliza固定了tips，并且测试了删除tips报错和教程中一样，开启了监管模式并且保留了trollstore和trollhelper(tips app)的后台进行延迟更新到16.6.1。 两台设备更新完之后出现了同样的问题： 升级完毕后应用列表的tips app不见了，进入AppStore搜索tips显示已购买可下载状态，点击下载无效。所有原系统trollstore安装的app无法打开：13pro显示为点击无效，ipad pro显示为已无法使用。 无法通过固定的tips重新install trollstore，无法通过trollstore重建图标缓存，无法通过fliza关闭监管模式。这种情况是不是只能等opa334开发新的安装方法才能解决了？
> > 
> > 
> > 是的，你目前只能等待 opa334 或者其他人找到新的安装方法。 根据你的描述，我猜测你与某些人一样，执行 chflags 命令时没移除后后面的 /Tips.app，应该锁定上层文件夹而不是 Tips.app 本身
> 
> 你好，刚刚我查看了13pro的后台发现还有trollstore，测试可以用后台打开，我将trollhelper改成了fitness，之后可以成功使用trollstore安装的程序了。目前ipad更新之后后台是空的，可能无法复现这种方法来激活trollstore了，我猜可能是运行内存只有4g的原因？。
> 
> 我可以确定我在执行命令的时候是移除了/tips.app。 通过fliza的历史，看到虽然tips app消失了，store也显示已购买可下载状态（下载无效），但是fliza里面依然有tips的文件夹，通过教程的取消固定之后，可以才能正常下载。这也能说明我之前的操作应该是没问题的。

我也是 提示 取消固定命令输错了，然后删除了提示，再商店里下载时闪一下没反应，然后我将trollhelper改成了fitness，一切正常，trollstore也能安装打开软件，不知道这个提示安装不回来对系统有没有影响

**Comment by Takagoz** [comment]
> > > > iphone 13pro 16.1.2更新到16.6.1，ipad pro 2018 15.0更新到16.6.1，之前完全按照教程设置，通过fliza固定了tips，并且测试了删除tips报错和教程中一样，开启了监管模式并且保留了trollstore和trollhelper(tips app)的后台进行延迟更新到16.6.1。 两台设备更新完之后出现了同样的问题： 升级完毕后应用列表的tips app不见了，进入AppStore搜索tips显示已购买可下载状态，点击下载无效。所有原系统trollstore安装的app无法打开：13pro显示为点击无效，ipad pro显示为已无法使用。 无法通过固定的tips重新install trollstore，无法通过trollstore重建图标缓存，无法通过fliza关闭监管模式。这种情况是不是只能等opa334开发新的安装方法才能解决了？
> > > 
> > > 
> > > 是的，你目前只能等待 opa334 或者其他人找到新的安装方法。 根据你的描述，我猜测你与某些人一样，执行 chflags 命令时没移除后后面的 /Tips.app，应该锁定上层文件夹而不是 Tips.app 本身
> > 
> > 
> > 你好，刚刚我查看了13pro的后台发现还有trollstore，测试可以用后台打开，我将trollhelper改成了fitness，之后可以成功使用trollstore安装的程序了。目前ipad更新之后后台是空的，可能无法复现这种方法来激活trollstore了，我猜可能是运行内存只有4g的原因？。
> > 我可以确定我在执行命令的时候是移除了/tips.app。 通过fliza的历史，看到虽然tips app消失了，store也显示已购买可下载状态（下载无效），但是fliza里面依然有tips的文件夹，通过教程的取消固定之后，可以才能正常下载。这也能说明我之前的操作应该是没问题的。
> 
> 我也是 提示 取消固定命令输错了，然后删除了提示，再商店里下载时闪一下没反应，然后我将trollhelper改成了fitness，一切正常，trollstore也能安装打开软件，不知道这个提示安装不回来对系统有没有影响

你说的这个是两个问题，取消固定命令输错了且删除了提示是否对系统和trollstore有影响，将trollhelper设置成fitness而不是tips是否对系统和trollstore有影响。
第一个问题，我没看懂，取消固定命令输错成什么了？输入的字段缺少了什么？输错之后有什么提示吗？
第二个问题，没影响，trollhelper注入到fitness和tips实际上是一样的。

**Comment by invalidunit** [comment]
> 我应该是 提示 取消固定命令输错了，然后删除了提示，fliza里面依然有tips的文件夹，重新在商店里下载时没有成功，然后我将trollhelper改成了fitness，一切正常，trollstore也能安装打开软件，不知道这个提示安装不回来对系统有没有影响

没有影响，只需保证你设备有一个可以正常工作的 TrollHelper，可用于刷新图标缓存即可。

**Comment by zlfengshare** [comment]
> > > > > iphone 13pro 16.1.2更新到16.6.1，ipad pro 2018 15.0更新到16.6.1，之前完全按照教程设置，通过fliza固定了tips，并且测试了删除tips报错和教程中一样，开启了监管模式并且保留了trollstore和trollhelper(tips app)的后台进行延迟更新到16.6.1。 两台设备更新完之后出现了同样的问题： 升级完毕后应用列表的tips app不见了，进入AppStore搜索tips显示已购买可下载状态，点击下载无效。所有原系统trollstore安装的app无法打开：13pro显示为点击无效，ipad pro显示为已无法使用。 无法通过固定的tips重新install trollstore，无法通过trollstore重建图标缓存，无法通过fliza关闭监管模式。这种情况是不是只能等opa334开发新的安装方法才能解决了？
> > > > 
> > > > 
> > > > 是的，你目前只能等待 opa334 或者其他人找到新的安装方法。 根据你的描述，我猜测你与某些人一样，执行 chflags 命令时没移除后后面的 /Tips.app，应该锁定上层文件夹而不是 Tips.app 本身
> > > 
> > > 
> > > 你好，刚刚我查看了13pro的后台发现还有trollstore，测试可以用后台打开，我将trollhelper改成了fitness，之后可以成功使用trollstore安装的程序了。目前ipad更新之后后台是空的，可能无法复现这种方法来激活trollstore了，我猜可能是运行内存只有4g的原因？。
> > > 我可以确定我在执行命令的时候是移除了/tips.app。 通过fliza的历史，看到虽然tips app消失了，store也显示已购买可下载状态（下载无效），但是fliza里面依然有tips的文件夹，通过教程的取消固定之后，可以才能正常下载。这也能说明我之前的操作应该是没问题的。
> > 
> > 
> > 我也是 提示 取消固定命令输错了，然后删除了提示，再商店里下载时闪一下没反应，然后我将trollhelper改成了fitness，一切正常，trollstore也能安装打开软件，不知道这个提示安装不回来对系统有没有影响
> 
> 你说的这个是两个问题，取消固定命令输错了且删除了提示是否对系统和trollstore有影响，将trollhelper设置成fitness而不是tips是否对系统和trollstore有影响。 第一个问题，我没看懂，取消固定命令输错成什么了？输入的字段缺少了什么？输错之后有什么提示吗？ 第二个问题，没影响，trollhelper注入到fitness和tips实际上是一样的。只要你不用到tips app，就没影响，如果需要用到tips的话，解决第一个问题就行

嗯，希望没影响就好，第一个问题输错原因是，复制的命令是对的，只是我用的搜狗输入法，粘贴完，没有回车的按钮，就想消掉命令换个输入法重新来。。。也是比较不懂的做法，消了一半（不全的路径）就按了那个esc的按钮，然后就出现一系列命令行，就退出filza重新输入取消固定的命令，输完等了一会才有反应，然后又是出现一系列命令行（哎。。。好菜），然后再把提示删除就安装不回来了。
出现的命令行如下
![IMG_2586](https://github.com/invalidunit/chflags_trollhelper/assets/844969/30586ace-01a4-44ba-999b-adcd44a5bdce)
