### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Ma-yeah** [invalidunit/chflags_trollhelper#5]
我按照 `四、使用 Filza 锁定已有的 TrollHelper 防止更新过程中被系统替换为新版的 Tips` 中的方法，成功锁定了。
之后不小心在 filza 中的另一个目录点了粘贴，然后就把 `Tips.app` 粘贴过来了，接着想要删除掉，就无法删除了，提示 `未能储存该文件，因为您没有权限`。
怎么可以删除掉这个误粘贴的 `Tips.app` ?

**Comment by invalidunit** [comment]
> 我按照 `四、使用 Filza 锁定已有的 TrollHelper 防止更新过程中被系统替换为新版的 Tips` 中的方法，成功锁定了。 之后不小心在 filza 中的另一个目录点了粘贴，然后就把 `Tips.app` 粘贴过来了，接着想要删除掉，就无法删除了，提示 `未能储存该文件，因为您没有权限`。 怎么可以删除掉这个误粘贴的 `Tips.app` ?

https://github.com/invalidunit/chflags_trollhelper#6-2-%E6%8E%A5%E4%B8%8B%E6%9D%A5%E6%89%93%E5%BC%80-filza-%E8%A7%A3%E9%99%A4-tips-%E9%94%81%E5%AE%9A

只需按照 6-2 的步骤解锁多出来的 Tips

**Comment by Ma-yeah** [comment]
好了，感谢大佬。
之前是因为路径中有空格，执行会有问题，拿单引号裹起来就可以了
