### ISSUE TITLE
解锁后删不掉提示，再解锁出现如下代码

### ISSUE THREAD

**Issue by DemonZaa** [invalidunit/chflags_trollhelper#7]
![IMG_5722](https://github.com/invalidunit/chflags_trollhelper/assets/152727433/c06b565c-305e-431b-9c82-c3ef50a970f6)

更新完解锁tips，严格按照教程删除tips.app，然后粘贴代码，然后删除提示，AppStore里面显示的打开按钮，怎么点都无反应，之后重启，提示又回到了桌面，再想解锁一次就出现了图片这样，在filza里面删除tips显示删除失败，这该怎么解锁啊

**Comment by invalidunit** [comment]
> ![IMG_5725](https://private-user-images.githubusercontent.com/152727433/287495186-1bd0c1f6-b002-411e-b1c3-bc560d5a26c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzQ0MzksIm5iZiI6MTcwMTU3NDEzOSwicGF0aCI6Ii8xNTI3Mjc0MzMvMjg3NDk1MTg2LTFiZDBjMWY2LWIwMDItNDExZS1iMWMzLWJjNTYwZDVhMjZjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjEzODg3YmU4YTIzMzM0ZWQ1MDk4MjRkYjM3ZmUxNWI0NzM2NWYwMGM4NDFmYTJiMTJiNTk5MjQ5Zjg3NmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mm3QNHFRwYdnEoguBjpxKsZ4WOXi10AxrsDtMkeKt8w) 全都重弄过好几遍了，一粘贴就自动多出来一行变成这样，…….

你现在这个看着没问题，直接回车运行
