### ISSUE TITLE
已越狱设备是否需要先清除越狱

### ISSUE THREAD

**Issue by moonskyer** [invalidunit/chflags_trollhelper#9]
你好，IOS13在升级到16.6前，需要先恢复到未越狱状态吗？我到这一步，越狱状态时关机重新开启设备，这个时候Filza、TrollHelper、tips打开就会闪退，而且后台中只有提示了，如果升级到16.6担心无法进行更新后的处理那一节。

**Comment by invalidunit** [comment]
> 好，IOS13在升级到16.6前，需要先恢复到未越狱状态吗？我到这一步，越狱状态时关机重新开启设备，这个时候Filza、TrollHelper、tips打开你就会闪退，而且后台只有提示了，如果升级到16.6担心无法进行后面的处理那句话。

不需要，大的跨版本基本都是全量包，加上 iOS12.2 开始（好像）检测到你系统区修改过将会强制下载全量包覆盖修改，主要是确保你的启动项不要被关闭了，例如 icp（小扫把）里面那一堆

**Comment by invalidunit** [comment]
> 你好，IOS13在升级到16.6前，需要先恢复到未越狱状态吗？我到这一步，越狱状态时关机重新开启设备，这个时候Filza、TrollHelper、tips打开就会闪退，而且后台中只有提示了，如果升级到16.6担心无法进行更新后的处理那一节。

至于更新后，越狱安装的 Filza 将会直接消失，请手动 从 TIGISoftware 官网下载 Filza 给 TrollStore 安装，进行解锁步骤

**Comment by moonskyer** [comment]
> > 好，IOS13在升级到16.6前，需要先恢复到未越狱状态吗？我到这一步，越狱状态时关机重新开启设备，这个时候Filza、TrollHelper、tips打开你就会闪退，而且后台只有提示了，如果升级到16.6担心无法进行后面的处理那句话。
> 
> 不需要，大的跨版本基本都是全量包，加上 iOS12.2 开始（好像）检测到你系统区修改过将会强制下载全量包覆盖修改，主要是确保你的启动项不要被关闭了，例如 icp（小扫把）里面那一堆

越狱这块理解了，因为延迟升级的教程里https://dhinakg.github.io/delayed-otas.html，给出的方法是ios14.5以下的走的是越狱开启监管最后升级前恢复未越狱，所以比较困惑。  麻烦再说一下icp（小扫把）启动项不要被关闭了这个是什么意思，整个文档中没有涉及到这块的内容

**Comment by invalidunit** [comment]
> > > 好，IOS13在升级到16.6前，需要先恢复到未越狱状态吗？我到这一步，越狱状态时关机重新开启设备，这个时候Filza、TrollHelper、tips打开你就会闪退，而且后台只有提示了，如果升级到16.6担心无法进行后面的处理那句话。
> > 
> > 
> > 不需要，大的跨版本基本都是全量包，加上 iOS12.2 开始（好像）检测到你系统区修改过将会强制下载全量包覆盖修改，主要是确保你的启动项不要被关闭了，例如 icp（小扫把）里面那一堆
> 
> 越狱这块理解了，因为延迟升级的教程里[https://dhinakg.github.io/delayed-otas.html，给出的方法是ios14.5以下的走的是越狱开启监管最后升级前恢复未越狱，所以比较困惑。](https://dhinakg.github.io/delayed-otas.html%EF%BC%8C%E7%BB%99%E5%87%BA%E7%9A%84%E6%96%B9%E6%B3%95%E6%98%AFios14.5%E4%BB%A5%E4%B8%8B%E7%9A%84%E8%B5%B0%E7%9A%84%E6%98%AF%E8%B6%8A%E7%8B%B1%E5%BC%80%E5%90%AF%E7%9B%91%E7%AE%A1%E6%9C%80%E5%90%8E%E5%8D%87%E7%BA%A7%E5%89%8D%E6%81%A2%E5%A4%8D%E6%9C%AA%E8%B6%8A%E7%8B%B1%EF%BC%8C%E6%89%80%E4%BB%A5%E6%AF%94%E8%BE%83%E5%9B%B0%E6%83%91%E3%80%82) 麻烦再说一下icp（小扫把）启动项不要被关闭了这个是什么意思，整个文档中没有涉及到这块的内容

否，对于 iOS14 我也觉得不需要清楚越狱，因为所有系统区的修改都会被 OTA 覆盖，不过 iOS15 的 rootless 我确实不确定，因为释放文件的地方不一样，iOS15 还是手动清理以保证更新后不会有奇怪的空间占用比较好


至于 icp（iCleaner Pro），我的意思是如果你之前越狱过并且使用过的话，如果你使用过并且手动修改了启动项，我的建议是先手动打开这些启动项。
当然没用过更好，我这里的写法本身就是建立在从没越狱过的基础上写的。

**Comment by invalidunit** [comment]
![ec9a1ca43e16acf4b53f1cd7f53893cf_720](https://github.com/invalidunit/chflags_trollhelper/assets/35675770/c1f97a32-6d53-45f5-bb89-5825483f42c0)

**Comment by moonskyer** [comment]
> > > > 好，IOS13在升级到16.6前，需要先恢复到未越狱状态吗？我到这一步，越狱状态时关机重新开启设备，这个时候Filza、TrollHelper、tips打开你就会闪退，而且后台只有提示了，如果升级到16.6担心无法进行后面的处理那句话。
> > > 
> > > 
> > > 不需要，大的跨版本基本都是全量包，加上 iOS12.2 开始（好像）检测到你系统区修改过将会强制下载全量包覆盖修改，主要是确保你的启动项不要被关闭了，例如 icp（小扫把）里面那一堆
> > 
> > 
> > 越狱这块理解了，因为延迟升级的教程里[https://dhinakg.github.io/delayed-otas.html，给出的方法是ios14.5以下的走的是越狱开启监管最后升级前恢复未越狱，所以比较困惑。](https://dhinakg.github.io/delayed-otas.html%EF%BC%8C%E7%BB%99%E5%87%BA%E7%9A%84%E6%96%B9%E6%B3%95%E6%98%AFios14.5%E4%BB%A5%E4%B8%8B%E7%9A%84%E8%B5%B0%E7%9A%84%E6%98%AF%E8%B6%8A%E7%8B%B1%E5%BC%80%E5%90%AF%E7%9B%91%E7%AE%A1%E6%9C%80%E5%90%8E%E5%8D%87%E7%BA%A7%E5%89%8D%E6%81%A2%E5%A4%8D%E6%9C%AA%E8%B6%8A%E7%8B%B1%EF%BC%8C%E6%89%80%E4%BB%A5%E6%AF%94%E8%BE%83%E5%9B%B0%E6%83%91%E3%80%82) 麻烦再说一下icp（小扫把）启动项不要被关闭了这个是什么意思，整个文档中没有涉及到这块的内容
> 
> 否，对于 iOS14 我也觉得不需要清楚越狱，因为所有系统区的修改都会被 OTA 覆盖，不过 iOS15 的 rootless 我确实不确定，因为释放文件的地方不一样，iOS15 还是手动清理以保证更新后不会有奇怪的空间占用比较好
> 
> 至于 icp（iCleaner Pro），我的意思是如果你之前越狱过并且使用过的话，如果你使用过并且手动修改了启动项，我的建议是先手动打开这些启动项。 当然没用过更好，我这里的写法本身就是建立在从没越狱过的基础上写的。

ok多谢，那我去升级了，我能做的都做好了，冲一把看是好消息还是坏消息哈哈

**Comment by moonskyer** [comment]
> > > > 好，IOS13在升级到16.6前，需要先恢复到未越狱状态吗？我到这一步，越狱状态时关机重新开启设备，这个时候Filza、TrollHelper、tips打开你就会闪退，而且后台只有提示了，如果升级到16.6担心无法进行后面的处理那句话。
> > > 
> > > 
> > > 不需要，大的跨版本基本都是全量包，加上 iOS12.2 开始（好像）检测到你系统区修改过将会强制下载全量包覆盖修改，主要是确保你的启动项不要被关闭了，例如 icp（小扫把）里面那一堆
> > 
> > 
> > 越狱这块理解了，因为延迟升级的教程里[https://dhinakg.github.io/delayed-otas.html，给出的方法是ios14.5以下的走的是越狱开启监管最后升级前恢复未越狱，所以比较困惑。](https://dhinakg.github.io/delayed-otas.html%EF%BC%8C%E7%BB%99%E5%87%BA%E7%9A%84%E6%96%B9%E6%B3%95%E6%98%AFios14.5%E4%BB%A5%E4%B8%8B%E7%9A%84%E8%B5%B0%E7%9A%84%E6%98%AF%E8%B6%8A%E7%8B%B1%E5%BC%80%E5%90%AF%E7%9B%91%E7%AE%A1%E6%9C%80%E5%90%8E%E5%8D%87%E7%BA%A7%E5%89%8D%E6%81%A2%E5%A4%8D%E6%9C%AA%E8%B6%8A%E7%8B%B1%EF%BC%8C%E6%89%80%E4%BB%A5%E6%AF%94%E8%BE%83%E5%9B%B0%E6%83%91%E3%80%82) 麻烦再说一下icp（小扫把）启动项不要被关闭了这个是什么意思，整个文档中没有涉及到这块的内容
> 
> 否，对于 iOS14 我也觉得不需要清楚越狱，因为所有系统区的修改都会被 OTA 覆盖，不过 iOS15 的 rootless 我确实不确定，因为释放文件的地方不一样，iOS15 还是手动清理以保证更新后不会有奇怪的空间占用比较好
> 
> 至于 icp（iCleaner Pro），我的意思是如果你之前越狱过并且使用过的话，如果你使用过并且手动修改了启动项，我的建议是先手动打开这些启动项。 当然没用过更好，我这里的写法本身就是建立在从没越狱过的基础上写的。

ok多谢，我不涉及到越狱使用，那我去升级了，我能做的都做好了，等我消息！

![微信图片_20231203133232](https://github.com/invalidunit/chflags_trollhelper/assets/34910553/cfd6682c-d7bf-4c4f-8449-7d768de48156)
![微信图片_20231203133237](https://github.com/invalidunit/chflags_trollhelper/assets/34910553/b82e301d-430f-414b-80d0-b3c499f76965)
![微信图片_20231203133240](https://github.com/invalidunit/chflags_trollhelper/assets/34910553/17d48d04-18a6-4248-993b-6c2244936eb4)

**Comment by moonskyer** [comment]
结论来了，升级后Tips应用中的helper还存在，在tips中刷新后就可以继续后面步骤安装filza了，多谢大佬的教程！！！
![09fd83bb4082438f1288d80927834b1](https://github.com/invalidunit/chflags_trollhelper/assets/34910553/3415ea45-dcc8-48cc-9b72-58334df7b58d)
![f854dcea9417e4177311c8bb51ed43f](https://github.com/invalidunit/chflags_trollhelper/assets/34910553/220b8a35-a676-4f06-862e-f6a537f10819)
![33059d7f72b2b47a68d49346004dd8c](https://github.com/invalidunit/chflags_trollhelper/assets/34910553/e0125c94-683d-4c78-9e88-65d741d9c779)
